services:

  auth-service:
    container_name: auth-service
    build:
      context: ./apps/auth-service
      dockerfile: Dockerfile
    image: securebank/auth-service:local
    ports:
      - "8000:8000"
    environment:
      - SERVICE_NAME=auth-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - securebank-net

  account-service:
    container_name: account-service
    build:
      context: ./apps/account-service
      dockerfile: Dockerfile
    image: securebank/account-service:local
    ports:
      - "8001:8001"
    depends_on:
      auth-service:
        condition: service_healthy
    environment:
      - SERVICE_NAME=account-service
      - AUTH_SERVICE_URL=http://localhost:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - securebank-net

  transaction-service:
    container_name: transaction-service
    build:
      context: ./apps/transaction-service
      dockerfile: Dockerfile
    image: securebank/transaction-service:local
    ports:
      - "8002:8002"
    depends_on:
      auth-service:
        condition: service_healthy
    environment:
      - SERVICE_NAME=transaction-service
      - AUTH_SERVICE_URL=http://localhost:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - securebank-net

  notification-service:
    container_name: notification-service
    build:
      context: ./apps/notification-service
      dockerfile: Dockerfile
    image: securebank/notification-service:local
    ports:
      - "8003:8003"
    environment:
      - SERVICE_NAME=notification-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - securebank-net

networks:
  securebank-net:
    driver: bridge
