# Default values for securebank.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

namespace: securebank

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: 10-dd94ee1

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

# services:
#   auth:
#     name: auth-service
#     image: securebank/auth-service:local
#     port: 8000

#   account:
#     name: account-service
#     image: securebank/account-service:local
#     port: 8001

#   transaction:
#     name: transaction-service
#     image: securebank/transaction-service:local
#     port: 8002

#   notification:
#     name: notification-service
#     image: securebank/notification-service:local
#     port: 8003

services:
  auth:
    name: auth-service
    image:
      repository: securebank/auth-service
      tag: 10-dd94ee1
      pullPolicy: IfNotPresent
    port: 8000

  account:
    name: account-service
    image:
      repository: securebank/account-service
      tag: 10-dd94ee1
      pullPolicy: IfNotPresent
    port: 8001

  transaction:
    name: transaction-service
    image:
      repository: securebank/transaction-service
      tag: 10-dd94ee1
      pullPolicy: IfNotPresent
    port: 8002

  notification:
    name: notification-service
    image:
      repository: securebank/notification-service
      tag: 10-dd94ee1
      pullPolicy: IfNotPresent
    port: 8003
